name: Update JSON

on:
  repository_dispatch:
    types: [update]

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Write JSON
        run: |
          echo '${{ toJson(github.event.client_payload) }}' > room-status.json

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update room status"
          file_pattern: room-status.json
